server:
  port : 8799
#  ssl:
#    enabled: true
#    key-store: key_store.jks
#    key-store-password: jemma12
#    #key-password: K3XpNLrkvi9YHfWl-twewvNlFnSMUmGl
#    key-alias: devware.shop
#    trust-store: trustcert.jks
#    trust-store-password: jemma12

  
#    enabled: true
#    key-store: keystore
#    key-store-type: PKCS12
#    key-store-password: jemma


# Oracle Connect
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: jemtalk-group
#      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      max-poll-records: 1000
      properties:
        auto.create.topics.enable: false
        metadata.max.age.ms: 300
        spring:
          json:
            value:
              default:
                type: com.oracle.JemTalk.dto.ChatMessage
              trusted:
                packages: com.oracle.JemTalk.dto.*
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  # File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
   url: jdbc:oracle:thin:@localhost:1521/xe

   username: kafka
   password: tiger
   driver-class-name: oracle.jdbc.driver.OracleDriver
   
  # view Resolver
  mvc:
    view:
     prefix: /WEB-INF/views/
     suffix: .jsp

#Mybatis classpath는 resource
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL
      